version: '2.3'

services:

  my_container:
    image: my_image
    container_name: my_container
    working_dir: /code
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/code
      - /media/enric/enric_hdd/datasets/aichallenge/track3:/data
    command: tail /dev/null -f
